# Using Numpy for matrix

In [2]:
import numpy as np

M = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(M)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


## Especificando el tipo de data

In [6]:
M = np.array([[1,2,3],[4,5,6],[7,8,9]],dtype=complex)
print(M)
print()
M = np.array([[1,2,3],[4,5,6],[7,8,9]],dtype=float)
print(M)


[[1.+0.j 2.+0.j 3.+0.j]
 [4.+0.j 5.+0.j 6.+0.j]
 [7.+0.j 8.+0.j 9.+0.j]]

[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]


## Llamar un elemento

In [7]:
M[0][2] # elemento sencillo

3.0

In [8]:
M[1] # Toda la fila

array([4., 5., 6.])

In [9]:
M[1,:] # Tambien valido

array([4., 5., 6.])

In [10]:
M[:,0] # Toda la columna

array([1., 4., 7.])

## Matriz de ceros

In [11]:
print(np.zeros((5,7)))

[[0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]


## Matriz de unos

In [12]:
print(np.ones((5,7)))

[[1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]]


## Matriz diagonal

In [13]:
x = [1,2,3,4]
N = np.diag(x)
print(N)

[[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]]


## Para obtener la diagonal

In [14]:
np.diag(N)

array([1, 2, 3, 4])

## Dimensiones

In [15]:
np.shape(M)

(3, 3)

## Sumar todos los elementos

In [16]:
np.sum(M)

45.0

### Sumar por filas

In [17]:
np.sum(M,axis=0)

array([12., 15., 18.])

### Sumar por columnas

In [18]:
np.sum(M,axis=1)

array([ 6., 15., 24.])

## Producto de todos los elementos de la matriz

In [19]:
np.prod(M)

362880.0

## Media de todos los elementos de la matriz

In [20]:
np.mean(M)

5.0

### Media por lineas

In [21]:
np.mean(M, axis=0)

array([4., 5., 6.])

### Media por columnas

In [22]:
np.mean(M,axis=1)

array([2., 5., 8.])

## Transpuesta

In [28]:
print(M)
print()
print(M.transpose())

[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]

[[1. 4. 7.]
 [2. 5. 8.]
 [3. 6. 9.]]


## Traza de matriz

In [29]:
M.trace()

15.0

## Suma de matrices

In [31]:
A = np.array([[1,2],[2,0]])
B = np.array([[3,0],[1,4]])
print(A+B)

[[4 2]
 [3 4]]


## Producto matriz por escalar

In [32]:
print(5*A)

[[ 5 10]
 [10  0]]


## Producto de matrices

In [33]:
print(A.dot(B))

[[5 8]
 [6 0]]


### Producto de cada elemento por posicion

In [34]:
print(A*B)

[[3 0]
 [2 0]]


## Protencia

In [35]:
print(np.linalg.matrix_power(A,5))

[[65 58]
 [58 36]]


## Rango en inversa

In [36]:
np.linalg.matrix_rank(A)

2

In [43]:
print(M)
print("Note that M is {0}".format(np.shape(M)))
print("but the range is: {0}".format(np.linalg.matrix_rank(M)))

[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]
Note that M is (3, 3)
but the range is: 2


## La inversa

In [46]:
print(A)
print("La inversa es:")
print(np.linalg.inv(A))

print("El producto es:")
print(A.dot(np.linalg.inv(A)))

[[1 2]
 [2 0]]
La inversa es:
[[ 0.    0.5 ]
 [ 0.5  -0.25]]
El producto es:
[[1. 0.]
 [0. 1.]]
